spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ds_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: debug
    com.example.ds: debug
  file:
    name: logs/ds-demo-dev.log 